// src/components/Services/Services.tsx
import { useState } from "react";
import ServiceItem from "./ServiceItem";
import { servicesData } from "./servicesData";
import React from "react";
// Using global styles from index.css

const Services = () => {
  const [activeServiceId, setActiveServiceId] = useState<string | null>(null);

  const handleServiceClick = (serviceId: string) => {
    // Toggle the service - if it's already active, close it, otherwise open it
    setActiveServiceId(activeServiceId === serviceId ? null : serviceId);
  };

  return (
    <section className="services-section-marzipan" id="services-section">
      <div className="services-intro-text-container">
        <div className="services-intro-text">Services —</div>
        <p>
          My work is grounded in presence to ensure every project is approached
          with clear intention and purpose. Every partnership is built on trust
          and transparency, and every engagement begins with a deep alignment
          session to define the scope and vision together. The listed starting
          prices offer a baseline; a final quote will be tailored to your
          project's specific needs after our initial session.
        </p>
      </div>

      <div className="services-list-container">
        <div className="services-list" id="services-list-items">
          {servicesData.map((service) => (
            <ServiceItem
              key={service.id}
              service={service}
              isActive={activeServiceId === service.id}
              onClick={handleServiceClick}
            />
          ))}
        </div>
      </div>
    </section>
  );
};

export default Services;

// src/lib/components/Services.svelte
<script lang="ts">
  import ServiceItem from './ServiceItem.svelte';
  import { servicesData } from '$lib/data/servicesData';

  let activeServiceId: string | null = $state(null);

  function handleServiceClick(serviceId: string) {
    activeServiceId = activeServiceId === serviceId ? null : serviceId;
  }
</script>

<section class="services-section-marzipan" id="services-section">
  <div class="services-intro-text-container">
    <div class="services-intro-text">Services —</div>
    <p>
      My work is grounded in presence to ensure every project is approached
      with clear intention and purpose. Every partnership is built on trust
      and transparency, and every engagement begins with a deep alignment
      session to define the scope and vision together. The listed starting
      prices offer a baseline; a final quote will be tailored to your
      project's specific needs after our initial session.
    </p>
  </div>

  <div class="services-list-container">
    <div class="services-list" id="services-list-items">
      {#each servicesData as service (service.id)}
        <ServiceItem
          {service}
          isActive={activeServiceId === service.id}
          onclick={handleServiceClick}
        />
      {/each}
    </div>
  </div>
</section>
