// src/components/Testimonials/TestimonialItem.tsx
import React from "react";
import { TestimonialItemProps } from "../../types/index";

const TestimonialItem = ({ testimonial }: TestimonialItemProps) => {
  const renderStars = (rating: number) => {
    return Array.from({ length: 5 }, (_, index) => (
      <span
        key={index}
        className={`testimonial-star ${index < rating ? "filled" : ""}`}
      >
        ★
      </span>
    ));
  };

  return (
    <div className="testimonial-item">
      <div className="testimonial-content">
        <div className="testimonial-rating">
          {renderStars(testimonial.rating)}
        </div>
        <blockquote className="testimonial-quote">
          "{testimonial.content}"
        </blockquote>
        <div className="testimonial-author">
          <div className="testimonial-name">{testimonial.name}</div>
          <div className="testimonial-company">
            {testimonial.role} at {testimonial.company}
          </div>
        </div>
      </div>
    </div>
  );
};

export default TestimonialItem;

// src/lib/components/TestimonialItem.svelte
<script lang="ts">
  import type { Testimonial } from '$lib/types/index';

  let { testimonial }: { testimonial: Testimonial } = $props();
</script>

<div class="testimonial-item">
  <div class="testimonial-content">
    <div class="testimonial-rating">
      {#each Array.from({ length: 5 }) as _, index}
        <span class="testimonial-star {index < testimonial.rating ? 'filled' : ''}">
          ★
        </span>
      {/each}
    </div>
    <blockquote class="testimonial-quote">
      "{testimonial.content}"
    </blockquote>
    <div class="testimonial-author">
      <div class="testimonial-name">{testimonial.name}</div>
      <div class="testimonial-company">
        {testimonial.role} at {testimonial.company}
      </div>
    </div>
  </div>
</div>
